[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacksPlan]
providers = ["python"]

[[build.nixpacksPlan.phases.setup]]
name = "Setup Python"

[[build.nixpacksPlan.phases.install]]
name = "Install Dependencies"

[[build.nixpacksPlan.phases.build]]
name = "Build"

[deploy.healthcheck]
path = "/health"
timeout = 100
